# Site settings
title: Conor Patrick
email: conorpp@vt.edu

description: > # this means to ignore newlines until "baseurl:"
    A few of my pictures

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://photosby.conorpp.com" # the base hostname & protocol for your site
twitter_username: _conorpp
github_username:  conorpp

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
