#!/usr/bin/env bash

: ${GALLOC:?"Need to set GALLOC to dir"}
: ${SYNCSCRIPT:?"Need to set SYNCSCRIPT to script"}

if [[ ! -x $SYNCSCRIPT ]] ; then echo "SYNCSCRIPT is not executable" && exit ; fi
if [[ ! -d $GALLOC ]] ; then echo "GALLOC is not a dir" && exit ; fi

cur=`pwd`
cd $GALLOC/.. && eval $SYNCSCRIPT
cd $cur

moved=0

while read i
do
    bname=$(basename "$i")
    if [[ "$i" == *"/gallary/"*  && ! -f "images/gallary/$bname" ]]
    then
        echo moving $bname to gallary
        cp "$i" images/gallary

        moved=1
    elif [[ "$i" == *"/food/"*  && ! -f "images/food/$bname" ]] ; then
        echo moving $bname to food
        cp "$i" images/food
        moved=1
    fi

done < <(find $GALLOC/food $GALLOC/gallary -type f )

while read i
do
    bname=$(basename "$i")
    if [[ ! -f "$GALLOC/gallary/$bname" ]] || [[ ! -f "$GALLOC/food/$bname" ]]
    then
        if [[ "$i" == *"/gallary/"* ]] || [[ "$i" == *"/food/"* ]] ; then
            rm "$i" "$(find images/originals/ -name '$bname')" -f
            echo "$(find images/originals/ -name '$bname')"
        fi
    fi

done < <(find images/gallary images/food -type f)

if [[ $moved -eq 1 ]]
then
    echo 'resizing'
    cd images && ./Link.bash
    git checkout gh-pages
    git pull
    git merge master
    git add . -a
    git commit -m 'new pics'
    git push
fi


