#!/usr/bin/env bash

: ${GALLOC:?"Need to set GALLOC to dir"}
: ${SYNCSCRIPT:?"Need to set SYNCSCRIPT to script"}

if [[ ! -x $SYNCSCRIPT ]] ; then echo "SYNCSCRIPT is not executable" && exit ; fi
if [[ ! -d $GALLOC ]] ; then echo "GALLOC is not a dir" && exit ; fi

cur=`pwd`
cd $GALLOC/.. && eval $SYNCSCRIPT
cd $cur

moved=0

while read i
do
    bname=$(basename "$i")
    if [[ "$i" == *"/gallary/"*  && ! -f "images/gallary/$bname" ]]
    then
        echo moving $bname to gallary
        cp "$i" images/gallary

        moved=1
    elif [[ "$i" == *"/food/"*  && ! -f "images/food/$bname" ]] ; then
        echo moving $bname to food
        cp "$i" images/food
        moved=1
    fi

done < <(find $GALLOC/food $GALLOC/gallary -type f )

while read i
do
    bname=$(basename "$i")
        
    if [[ "$i" == *"/gallary/"* ]] ; then
        if [[ ! -f "$GALLOC/gallary/$bname" ]] ; then
            echo "removing $i, $(find images/originals/ -name "$bname")"
            rm "$i" "$(find images/originals/ -name "$bname")" 
            moved=1
        fi
    fi

    if [[ "$i" == *"/food/"* ]] ; then

        if [[ ! -f "$GALLOC/food/$bname" ]] ; then
            echo "removing $i"
            rm "$i" "$(find images/originals/ -name "$bname")"

            moved=1
        fi

    fi

done < <(find images/gallary images/food -type f)

if [[ $moved -eq 1 ]]
then
    echo 'resizing'
    cd images && ./Link.bash
fi

if [[ `git status` == *"Your branch is ahead of 'origin/gh-pages'"* ]] || [[ `git status` == *"Untracked files"* ]] || [[ `git status` == *"Changes to be committed"* ]]; then
    git checkout gh-pages
    git pull
    git merge master
    git add . --all
    git commit -m 'new pics'
    git push
fi

