#!/usr/bin/env python
import os
import json, sys

if len(sys.argv) < 2:
    print 'Enter directory to get json for'
    sys.exit()

def path_to_dict(path):
    d = {'name': os.path.basename(path)}
    if os.path.isdir(path):
        d['type'] = "directory"
        d['children'] = [path_to_dict(os.path.join(path,x)) for x in os.listdir(path)]
    else:
        d['type'] = "file"
    return d

print json.dumps(path_to_dict(sys.argv[1]))
